

-- MOCK DATA GENERATED BY SCRIPT
INSERT INTO `admin_audit_logs` (`id`, `admin_id`, `action`, `entity_type`, `entity_id`, `old_values`, `new_values`, `ip_address`, `created_at`) VALUES 
(NULL, 1, 'Test Action 73', 'Test Entity type 40', 1, 'Test Old values 60', 'Test New values 26', 'Test Ip address 18', NOW()),
(NULL, 1, 'Test Action 84', 'Test Entity type 68', 1, 'Test Old values 72', 'Test New values 56', 'Test Ip address 8', NOW()),
(NULL, 1, 'Test Action 62', 'Test Entity type 59', 1, 'Test Old values 54', 'Test New values 77', 'Test Ip address 78', NOW()),
(NULL, 1, 'Test Action 35', 'Test Entity type 44', 1, 'Test Old values 5', 'Test New values 27', 'Test Ip address 99', NOW()),
(NULL, 1, 'Test Action 68', 'Test Entity type 49', 1, 'Test Old values 91', 'Test New values 16', 'Test Ip address 33', NOW());

INSERT INTO `admin_notes` (`id`, `admin_id`, `user_id`, `note`, `created_at`) VALUES 
(NULL, 1, 5, 'Test Note 17', NOW()),
(NULL, 1, 5, 'Test Note 61', NOW()),
(NULL, 1, 4, 'Test Note 57', NOW()),
(NULL, 1, 6, 'Test Note 97', NOW()),
(NULL, 1, 6, 'Test Note 50', NOW());

INSERT INTO `admin_roles` (`admin_id`, `role_id`) VALUES 
(1, 1),
(1, 1),
(1, 1),
(1, 1),
(1, 1);

INSERT INTO `blocked_users` (`id`, `uuid`, `blocker_id`, `blocked_id`, `reason`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 1, 1, 'Test Reason 51', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 'Test Reason 94', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 'Test Reason 73', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 'Test Reason 80', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 'Test Reason 18', NOW(), '2026-08-01 12:00:00');

INSERT INTO `boosts` (`id`, `uuid`, `user_id`, `started_at`, `ends_at`, `multiplier`, `created_at`) VALUES 
(NULL, 1, 4, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 73.54, NOW()),
(NULL, 1, 4, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 33.72, NOW()),
(NULL, 1, 4, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 94.85, NOW()),
(NULL, 1, 4, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 97.63, NOW()),
(NULL, 1, 4, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 29.52, NOW());

INSERT INTO `cities` (`id`, `uuid`, `state_id`, `name`, `latitude`, `longitude`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 1, 'Test Name 26', 67.18, 15.60, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 79', 67.56, 41.21, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 85', 56.41, 77.13, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 18', 56.88, 67.99, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 61', 27.46, 62.96, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `conversations` (`id`, `uuid`, `match_id`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 1, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `conversation_participants` (`id`, `conversation_id`, `user_id`, `joined_at`, `last_read_message_id`, `typing_status`, `is_muted`) VALUES 
(NULL, 1, 6, '2026-08-01 12:00:00', 1, 1, 1),
(NULL, 1, 6, '2026-08-01 12:00:00', 1, 0, 1),
(NULL, 1, 4, '2026-08-01 12:00:00', 1, 1, 0),
(NULL, 1, 4, '2026-08-01 12:00:00', 1, 1, 0),
(NULL, 1, 6, '2026-08-01 12:00:00', 1, 0, 1);

INSERT INTO `countries` (`id`, `uuid`, `iso_code`, `name`, `phone_code`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Iso code 92', 'Test Name 24', 'Test Phone code 28', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Iso code 54', 'Test Name 15', 'Test Phone code 18', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Iso code 58', 'Test Name 80', 'Test Phone code 39', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Iso code 3', 'Test Name 68', 'Test Phone code 73', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Iso code 63', 'Test Name 27', 'Test Phone code 13', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `coupons` (`id`, `code`, `discount_percentage`, `discount_amount`, `max_uses`, `current_uses`, `expires_at`, `created_at`) VALUES 
(NULL, 'Test Code 49', 65.89, 98.53, 22, 63, '2026-08-01 12:00:00', NOW()),
(NULL, 'Test Code 87', 64.25, 47.17, 4, 26, '2026-08-01 12:00:00', NOW()),
(NULL, 'Test Code 66', 95.96, 78.39, 7, 53, '2026-08-01 12:00:00', NOW()),
(NULL, 'Test Code 99', 38.21, 83.58, 11, 23, '2026-08-01 12:00:00', NOW()),
(NULL, 'Test Code 79', 45.71, 60.68, 38, 62, '2026-08-01 12:00:00', NOW());

INSERT INTO `daily_user_counters` (`id`, `user_id`, `counter_date`, `likes_sent`, `super_likes_sent`, `rewinds_used`, `profiles_viewed`) VALUES 
(NULL, 6, '2026-08-01 12:00:00', 85, 88, 49, 4),
(NULL, 6, '2026-08-01 12:00:00', 9, 63, 37, 33),
(NULL, 5, '2026-08-01 12:00:00', 65, 32, 90, 71),
(NULL, 5, '2026-08-01 12:00:00', 80, 16, 6, 21),
(NULL, 4, '2026-08-01 12:00:00', 34, 13, 93, 22);

INSERT INTO `device_sessions` (`id`, `uuid`, `user_id`, `device_id`, `device_name`, `os_version`, `app_version`, `ip_address`, `last_active_at`, `is_active`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 5, 1, 'Test Device name 34', 'Test Os version 1', 'Test App version 48', 'Test Ip address 29', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'Test Device name 33', 'Test Os version 78', 'Test App version 98', 'Test Ip address 12', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 'Test Device name 100', 'Test Os version 53', 'Test App version 69', 'Test Ip address 40', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 'Test Device name 58', 'Test Os version 15', 'Test App version 50', 'Test Ip address 90', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 'Test Device name 9', 'Test Os version 2', 'Test App version 78', 'Test Ip address 19', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00');

INSERT INTO `device_tokens` (`id`, `uuid`, `user_id`, `device_type`, `push_token`, `is_active`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 5, 'IOS', 'Test Push token 39', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 'IOS', 'Test Push token 29', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 'IOS', 'Test Push token 90', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 'IOS', 'Test Push token 40', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 'IOS', 'Test Push token 80', 1, NOW(), '2026-08-01 12:00:00');

INSERT INTO `failed_jobs` (`id`, `uuid`, `connection`, `queue`, `payload`, `exception`, `failed_at`) VALUES 
(NULL, 1, 'Test Connection 50', 'Test Queue 47', 'Test Payload 1', 'Test Exception 65', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Connection 91', 'Test Queue 71', 'Test Payload 61', 'Test Exception 67', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Connection 19', 'Test Queue 85', 'Test Payload 2', 'Test Exception 64', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Connection 22', 'Test Queue 25', 'Test Payload 5', 'Test Exception 34', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Connection 67', 'Test Queue 89', 'Test Payload 26', 'Test Exception 58', '2026-08-01 12:00:00');

INSERT INTO `hobbies` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 62', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 12', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 78', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 46', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 61', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `interests` (`id`, `uuid`, `category_id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 1, 'Test Name 53', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 26', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 98', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 61', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 22', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `interest_categories` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 81', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 57', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 96', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 100', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 61', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `invoices` (`id`, `payment_id`, `user_id`, `invoice_number`, `billing_address`, `pdf_url`, `created_at`) VALUES 
(NULL, 1, 5, 'Test Invoice number 34', 'Test Billing address 42', 'https://example.com/image.jpg', NOW()),
(NULL, 1, 4, 'Test Invoice number 97', 'Test Billing address 68', 'https://example.com/image.jpg', NOW()),
(NULL, 1, 4, 'Test Invoice number 24', 'Test Billing address 31', 'https://example.com/image.jpg', NOW()),
(NULL, 1, 4, 'Test Invoice number 56', 'Test Billing address 94', 'https://example.com/image.jpg', NOW()),
(NULL, 1, 4, 'Test Invoice number 16', 'Test Billing address 40', 'https://example.com/image.jpg', NOW());

INSERT INTO `languages` (`id`, `uuid`, `code`, `name`, `native_name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Code 99', 'Test Name 38', 'Test Native name 98', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Code 48', 'Test Name 6', 'Test Native name 82', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Code 34', 'Test Name 47', 'Test Native name 61', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Code 8', 'Test Name 72', 'Test Native name 59', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Code 55', 'Test Name 100', 'Test Native name 74', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `location_history` (`id`, `user_id`, `latitude`, `longitude`, `created_at`) VALUES 
(NULL, 5, 72.60, 19.12, NOW()),
(NULL, 6, 49.72, 15.70, NOW()),
(NULL, 4, 84.19, 78.58, NOW()),
(NULL, 5, 91.71, 39.59, NOW()),
(NULL, 6, 98.69, 69.72, NOW());

INSERT INTO `login_history` (`id`, `uuid`, `user_id`, `ip_address`, `user_agent`, `location`, `status`, `failure_reason`, `created_at`) VALUES 
(NULL, 1, 6, 'Test Ip address 67', 'Test User agent 81', 'Test Location 23', 'SUCCESS', 'Test Failure reason 13', NOW()),
(NULL, 1, 4, 'Test Ip address 45', 'Test User agent 60', 'Test Location 4', 'SUCCESS', 'Test Failure reason 25', NOW()),
(NULL, 1, 4, 'Test Ip address 40', 'Test User agent 56', 'Test Location 66', 'SUCCESS', 'Test Failure reason 36', NOW()),
(NULL, 1, 4, 'Test Ip address 57', 'Test User agent 6', 'Test Location 15', 'SUCCESS', 'Test Failure reason 35', NOW()),
(NULL, 1, 5, 'Test Ip address 27', 'Test User agent 36', 'Test Location 7', 'SUCCESS', 'Test Failure reason 59', NOW());

INSERT INTO `love_languages` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 77', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 66', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 47', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 26', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 16', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `matches` (`id`, `uuid`, `user1_id`, `user2_id`, `compatibility_score`, `is_unmatched`, `unmatched_by_id`, `unmatched_reason`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 1, 1, 70.76, 1, 1, 'Test Unmatched reason 71', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 57.38, 1, 1, 'Test Unmatched reason 63', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 26.52, 1, 1, 'Test Unmatched reason 91', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 60.24, 0, 1, 'Test Unmatched reason 25', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 53.95, 0, 1, 'Test Unmatched reason 49', NOW(), '2026-08-01 12:00:00');

INSERT INTO `messages` (`id`, `uuid`, `conversation_id`, `sender_id`, `content`, `message_type`, `reply_to_id`, `status`, `is_pinned`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 1, 1, 'Test Content 100', 'TEXT', 1, 'SENT', 0, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 'Test Content 20', 'TEXT', 1, 'SENT', 0, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 'Test Content 6', 'TEXT', 1, 'SENT', 0, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 'Test Content 27', 'TEXT', 1, 'SENT', 1, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 'Test Content 39', 'TEXT', 1, 'SENT', 0, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `message_attachments` (`id`, `uuid`, `message_id`, `file_url`, `file_type`, `file_size_bytes`, `duration_seconds`, `metadata`, `created_at`) VALUES 
(NULL, 1, 1, 'https://example.com/image.jpg', 'Test File type 56', 16, 65, 'Test Metadata 71', NOW()),
(NULL, 1, 1, 'https://example.com/image.jpg', 'Test File type 12', 73, 53, 'Test Metadata 69', NOW()),
(NULL, 1, 1, 'https://example.com/image.jpg', 'Test File type 97', 21, 35, 'Test Metadata 45', NOW()),
(NULL, 1, 1, 'https://example.com/image.jpg', 'Test File type 68', 65, 10, 'Test Metadata 38', NOW()),
(NULL, 1, 1, 'https://example.com/image.jpg', 'Test File type 70', 85, 89, 'Test Metadata 75', NOW());

INSERT INTO `message_reactions` (`id`, `message_id`, `user_id`, `reaction_emoji`, `created_at`) VALUES 
(NULL, 1, 5, 'Test Reaction emoji 49', NOW()),
(NULL, 1, 5, 'Test Reaction emoji 61', NOW()),
(NULL, 1, 6, 'Test Reaction emoji 66', NOW()),
(NULL, 1, 5, 'Test Reaction emoji 97', NOW()),
(NULL, 1, 4, 'Test Reaction emoji 6', NOW());

INSERT INTO `moderation_queues` (`id`, `entity_type`, `entity_id`, `priority`, `status`, `flag_reason`, `created_at`) VALUES 
(NULL, 'USER_PROFILE', 1, 31, 'PENDING', 'Test Flag reason 9', NOW()),
(NULL, 'USER_PROFILE', 1, 24, 'PENDING', 'Test Flag reason 86', NOW()),
(NULL, 'USER_PROFILE', 1, 77, 'PENDING', 'Test Flag reason 4', NOW()),
(NULL, 'USER_PROFILE', 1, 43, 'PENDING', 'Test Flag reason 85', NOW()),
(NULL, 'USER_PROFILE', 1, 87, 'PENDING', 'Test Flag reason 6', NOW());

INSERT INTO `movie_genres` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 9', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 91', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 58', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 50', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 96', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `music_genres` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 98', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 13', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 14', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 77', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 59', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `notifications` (`id`, `uuid`, `user_id`, `type`, `title`, `body`, `reference_id`, `is_read`, `created_at`) VALUES 
(NULL, 1, 4, 'Test Type 40', 'Test Title 90', 'Test Body 40', 1, 1, NOW()),
(NULL, 1, 4, 'Test Type 43', 'Test Title 51', 'Test Body 77', 1, 0, NOW()),
(NULL, 1, 5, 'Test Type 76', 'Test Title 66', 'Test Body 15', 1, 0, NOW()),
(NULL, 1, 5, 'Test Type 34', 'Test Title 77', 'Test Body 65', 1, 1, NOW()),
(NULL, 1, 6, 'Test Type 22', 'Test Title 17', 'Test Body 92', 1, 1, NOW());

INSERT INTO `occupations` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 21', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 21', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 49', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 94', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 33', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `payments` (`id`, `uuid`, `user_id`, `amount`, `currency`, `status`, `payment_method`, `transaction_id`, `receipt_data`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 4, 18.63, 'Test Currency 56', 'PENDING', 'Test Payment method 53', 1, 'Test Receipt data 1', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 15.28, 'Test Currency 52', 'PENDING', 'Test Payment method 40', 1, 'Test Receipt data 44', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 95.96, 'Test Currency 29', 'PENDING', 'Test Payment method 40', 1, 'Test Receipt data 26', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 19.22, 'Test Currency 34', 'PENDING', 'Test Payment method 18', 1, 'Test Receipt data 32', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 63.39, 'Test Currency 61', 'PENDING', 'Test Payment method 14', 1, 'Test Receipt data 43', NOW(), '2026-08-01 12:00:00');

INSERT INTO `permissions` (`id`, `name`, `description`) VALUES 
(NULL, 'Test Name 83', 'Test Description 11'),
(NULL, 'Test Name 46', 'Test Description 60'),
(NULL, 'Test Name 60', 'Test Description 21'),
(NULL, 'Test Name 48', 'Test Description 41'),
(NULL, 'Test Name 54', 'Test Description 49');

INSERT INTO `personal_access_tokens` (`id`, `tokenable_type`, `tokenable_id`, `name`, `token`, `abilities`, `last_used_at`, `expires_at`, `created_at`, `updated_at`) VALUES 
(NULL, 'Test Tokenable type 45', 1, 'Test Name 26', 'Test Token 98', 'Test Abilities 3', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 'Test Tokenable type 78', 1, 'Test Name 99', 'Test Token 75', 'Test Abilities 9', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 'Test Tokenable type 97', 1, 'Test Name 44', 'Test Token 75', 'Test Abilities 40', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 'Test Tokenable type 56', 1, 'Test Name 86', 'Test Token 98', 'Test Abilities 72', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 'Test Tokenable type 97', 1, 'Test Name 96', 'Test Token 41', 'Test Abilities 31', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `pets` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 2', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 9', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 67', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 5', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 43', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `profile_prompts` (`id`, `uuid`, `prompt_text`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Prompt text 16', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Prompt text 10', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Prompt text 62', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Prompt text 30', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Prompt text 71', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `profile_visitors` (`id`, `visitor_id`, `visited_id`, `visited_at`) VALUES 
(NULL, 1, 1, '2026-08-01 12:00:00'),
(NULL, 1, 1, '2026-08-01 12:00:00'),
(NULL, 1, 1, '2026-08-01 12:00:00'),
(NULL, 1, 1, '2026-08-01 12:00:00'),
(NULL, 1, 1, '2026-08-01 12:00:00');

INSERT INTO `recommendation_queues` (`id`, `user_id`, `recommended_user_id`, `score`, `is_viewed`, `created_at`) VALUES 
(NULL, 5, 6, 85.23, 0, NOW()),
(NULL, 6, 6, 14.38, 0, NOW()),
(NULL, 5, 6, 78.49, 0, NOW()),
(NULL, 4, 4, 55.15, 1, NOW()),
(NULL, 4, 5, 99.13, 0, NOW());

INSERT INTO `refresh_tokens` (`id`, `uuid`, `user_id`, `session_id`, `token_hash`, `expires_at`, `is_revoked`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 4, 1, 'Test Token hash 98', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 'Test Token hash 60', '2026-08-01 12:00:00', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'Test Token hash 91', '2026-08-01 12:00:00', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 'Test Token hash 4', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'Test Token hash 90', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00');

INSERT INTO `reports` (`id`, `uuid`, `reporter_id`, `reported_id`, `reason_category`, `description`, `status`, `action_taken`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 4, 6, 'Test Reason category 72', 'Test Description 3', 'PENDING', 'Test Action taken 10', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 4, 'Test Reason category 77', 'Test Description 65', 'PENDING', 'Test Action taken 25', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 6, 'Test Reason category 98', 'Test Description 62', 'PENDING', 'Test Action taken 70', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 4, 'Test Reason category 34', 'Test Description 39', 'PENDING', 'Test Action taken 70', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 5, 'Test Reason category 51', 'Test Description 38', 'PENDING', 'Test Action taken 28', NOW(), '2026-08-01 12:00:00');

INSERT INTO `rewinds` (`id`, `uuid`, `user_id`, `swipe_id`, `created_at`) VALUES 
(NULL, 1, 6, 1, NOW()),
(NULL, 1, 6, 1, NOW()),
(NULL, 1, 4, 1, NOW()),
(NULL, 1, 6, 1, NOW()),
(NULL, 1, 4, 1, NOW());

INSERT INTO `roles` (`id`, `name`, `description`) VALUES 
(NULL, 'Test Name 51', 'Test Description 100'),
(NULL, 'Test Name 17', 'Test Description 34'),
(NULL, 'Test Name 1', 'Test Description 57'),
(NULL, 'Test Name 32', 'Test Description 51'),
(NULL, 'Test Name 45', 'Test Description 64');

INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES 
(1, 1),
(1, 1),
(1, 1),
(1, 1),
(1, 1);

INSERT INTO `security_logs` (`id`, `uuid`, `user_id`, `event_type`, `ip_address`, `details`, `created_at`) VALUES 
(NULL, 1, 6, 'Test Event type 36', 'Test Ip address 84', 'Test Details 63', NOW()),
(NULL, 1, 6, 'Test Event type 17', 'Test Ip address 81', 'Test Details 49', NOW()),
(NULL, 1, 6, 'Test Event type 83', 'Test Ip address 21', 'Test Details 23', NOW()),
(NULL, 1, 6, 'Test Event type 99', 'Test Ip address 11', 'Test Details 93', NOW()),
(NULL, 1, 4, 'Test Event type 51', 'Test Ip address 86', 'Test Details 59', NOW());

INSERT INTO `sports` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 15', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 36', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 93', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 26', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 13', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `states` (`id`, `uuid`, `country_id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 1, 'Test Name 23', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 7', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 78', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 100', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 52', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `subscription_plans` (`id`, `uuid`, `name`, `tier_level`, `billing_cycle`, `price`, `currency`, `features`, `is_active`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 'Test Name 41', 68, 'WEEKLY', 11.47, 'Test Currency 31', 'Test Features 28', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 17', 43, 'WEEKLY', 34.65, 'Test Currency 11', 'Test Features 9', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 58', 62, 'WEEKLY', 19.82, 'Test Currency 100', 'Test Features 53', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 10', 80, 'WEEKLY', 36.61, 'Test Currency 29', 'Test Features 36', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 35', 69, 'WEEKLY', 62.30, 'Test Currency 29', 'Test Features 100', 0, NOW(), '2026-08-01 12:00:00');

INSERT INTO `swipes` (`id`, `uuid`, `swiper_id`, `swipee_id`, `swipe_type`, `is_rewound`, `created_at`) VALUES 
(NULL, 1, 5, 5, 'LIKE', 1, NOW()),
(NULL, 1, 4, 4, 'LIKE', 0, NOW()),
(NULL, 1, 4, 6, 'LIKE', 0, NOW()),
(NULL, 1, 6, 5, 'LIKE', 0, NOW()),
(NULL, 1, 6, 4, 'LIKE', 0, NOW());

INSERT INTO `user_authentications` (`id`, `uuid`, `user_id`, `auth_provider`, `provider_id`, `password_hash`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 4, 1, 1, 'Test Password hash 10', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 1, 'Test Password hash 78', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 1, 'Test Password hash 67', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 1, 'Test Password hash 95', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 1, 'Test Password hash 71', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `user_hobbies` (`user_id`, `hobby_id`) VALUES 
(6, 1),
(5, 1),
(6, 1),
(5, 1),
(6, 1);

INSERT INTO `user_interests` (`user_id`, `interest_id`) VALUES 
(5, 1),
(5, 1),
(5, 1),
(4, 1),
(5, 1);

INSERT INTO `user_languages` (`user_id`, `language_id`) VALUES 
(4, 1),
(6, 1),
(5, 1),
(5, 1),
(6, 1);

INSERT INTO `user_locations` (`id`, `user_id`, `latitude`, `longitude`, `geohash`, `city_name`, `is_travel_mode`, `updated_at`) VALUES 
(NULL, 4, 64.30, 19.75, 'Test Geohash 61', 'Test City name 50', 0, '2026-08-01 12:00:00'),
(NULL, 5, 58.92, 90.53, 'Test Geohash 33', 'Test City name 2', 1, '2026-08-01 12:00:00'),
(NULL, 5, 83.87, 59.54, 'Test Geohash 5', 'Test City name 3', 1, '2026-08-01 12:00:00'),
(NULL, 4, 97.59, 47.68, 'Test Geohash 65', 'Test City name 4', 1, '2026-08-01 12:00:00'),
(NULL, 5, 17.33, 88.59, 'Test Geohash 27', 'Test City name 8', 1, '2026-08-01 12:00:00');

INSERT INTO `user_movie_genres` (`user_id`, `movie_genre_id`) VALUES 
(6, 1),
(5, 1),
(6, 1),
(4, 1),
(6, 1);

INSERT INTO `user_music_genres` (`user_id`, `music_genre_id`) VALUES 
(6, 1),
(5, 1),
(4, 1),
(5, 1),
(4, 1);

INSERT INTO `user_preference_children` (`user_id`, `children_id`) VALUES 
(4, 1),
(6, 1),
(4, 1),
(5, 1),
(5, 1);

INSERT INTO `user_preference_languages` (`user_id`, `language_id`) VALUES 
(4, 1),
(6, 1),
(6, 1),
(5, 1),
(6, 1);

INSERT INTO `user_preference_pets` (`user_id`, `pets_id`) VALUES 
(5, 1),
(5, 1),
(6, 1),
(4, 1),
(6, 1);

INSERT INTO `user_preference_politics` (`user_id`, `political_view_id`) VALUES 
(6, 1),
(5, 1),
(6, 1),
(5, 1),
(4, 1);

INSERT INTO `user_profile_prompts` (`id`, `uuid`, `user_id`, `prompt_id`, `answer_text`, `display_order`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 4, 1, 'Test Answer text 92', 94, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'Test Answer text 5', 30, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'Test Answer text 61', 31, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 'Test Answer text 58', 50, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 'Test Answer text 49', 44, NOW(), '2026-08-01 12:00:00');

INSERT INTO `user_sports` (`user_id`, `sport_id`) VALUES 
(6, 1),
(6, 1),
(6, 1),
(4, 1),
(6, 1);

INSERT INTO `user_subscriptions` (`id`, `uuid`, `user_id`, `plan_id`, `status`, `platform`, `platform_subscription_id`, `starts_at`, `ends_at`, `auto_renew`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 4, 1, 'ACTIVE', 'APPLE', 1, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 'ACTIVE', 'APPLE', 1, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 'ACTIVE', 'APPLE', 1, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 'ACTIVE', 'APPLE', 1, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'ACTIVE', 'APPLE', 1, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00');

INSERT INTO `user_videos` (`id`, `uuid`, `user_id`, `video_url`, `thumbnail_url`, `duration_seconds`, `display_order`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 4, 1, 'https://example.com/image.jpg', 42, 63, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 'https://example.com/image.jpg', 45, 9, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'https://example.com/image.jpg', 48, 95, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 'https://example.com/image.jpg', 11, 18, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 'https://example.com/image.jpg', 44, 16, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `verification_requests` (`id`, `uuid`, `user_id`, `selfie_photo_url`, `status`, `reviewed_by`, `rejection_reason`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 4, 'https://example.com/image.jpg', 'PENDING', 69, 'Test Rejection reason 27', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 'https://example.com/image.jpg', 'PENDING', 81, 'Test Rejection reason 42', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 'https://example.com/image.jpg', 'PENDING', 25, 'Test Rejection reason 57', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 'https://example.com/image.jpg', 'PENDING', 43, 'Test Rejection reason 38', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 'https://example.com/image.jpg', 'PENDING', 80, 'Test Rejection reason 30', NOW(), '2026-08-01 12:00:00');

INSERT INTO `wallet_transactions` (`id`, `uuid`, `wallet_id`, `transaction_type`, `item_type`, `amount`, `description`, `created_at`) VALUES 
(NULL, 1, 1, 'EARN', 'COINS', 14, 'Test Description 1', NOW()),
(NULL, 1, 1, 'EARN', 'COINS', 86, 'Test Description 30', NOW()),
(NULL, 1, 1, 'EARN', 'COINS', 39, 'Test Description 77', NOW()),
(NULL, 1, 1, 'EARN', 'COINS', 14, 'Test Description 31', NOW()),
(NULL, 1, 1, 'EARN', 'COINS', 13, 'Test Description 52', NOW());

INSERT INTO `explore_interests` (`id`, `name`, `icon`, `sort_order`, `created_at`) VALUES 
(NULL, 'Test Name 54', 'https://example.com/image.jpg', 22, NOW()),
(NULL, 'Test Name 2', 'https://example.com/image.jpg', 3, NOW()),
(NULL, 'Test Name 55', 'https://example.com/image.jpg', 93, NOW()),
(NULL, 'Test Name 73', 'https://example.com/image.jpg', 91, NOW()),
(NULL, 'Test Name 92', 'https://example.com/image.jpg', 96, NOW());

INSERT INTO `explore_trending_categories` (`id`, `name`, `image_url`, `sort_order`, `created_at`) VALUES 
(NULL, 'Test Name 5', 'https://example.com/image.jpg', 2, NOW()),
(NULL, 'Test Name 9', 'https://example.com/image.jpg', 16, NOW()),
(NULL, 'Test Name 51', 'https://example.com/image.jpg', 94, NOW()),
(NULL, 'Test Name 2', 'https://example.com/image.jpg', 75, NOW()),
(NULL, 'Test Name 70', 'https://example.com/image.jpg', 66, NOW());

INSERT INTO `user_daily_picks` (`id`, `user_id`, `target_user_id`, `created_at`) VALUES 
(NULL, 4, 6, NOW()),
(NULL, 6, 4, NOW()),
(NULL, 6, 6, NOW()),
(NULL, 4, 6, NOW()),
(NULL, 6, 5, NOW());

INSERT INTO `user_interactions` (`id`, `user_id`, `target_user_id`, `type`, `created_at`) VALUES 
(NULL, 4, 4, 'LIKE', NOW()),
(NULL, 6, 6, 'LIKE', NOW()),
(NULL, 6, 5, 'LIKE', NOW()),
(NULL, 6, 6, 'LIKE', NOW()),
(NULL, 4, 5, 'LIKE', NOW());

INSERT INTO `user_views` (`id`, `viewer_id`, `user_id`, `viewed_at`) VALUES 
(NULL, 6, 5, NOW()),
(NULL, 5, 6, NOW()),
(NULL, 4, 5, NOW()),
(NULL, 6, 5, NOW()),
(NULL, 6, 6, NOW());

