

-- MOCK DATA GENERATED BY SCRIPT
INSERT INTO `admins` (`id`, `uuid`, `first_name`, `last_name`, `email`, `password_hash`, `is_active`, `created_at`, `updated_at`, `deleted_at`, `admin_id`, `action`, `entity_type`, `entity_id`, `old_values`, `new_values`, `ip_address`, `user_id`, `note`, `role_id`, `blocker_id`, `blocked_id`, `reason`, `started_at`, `ends_at`, `multiplier`, `name`, `state_id`, `latitude`, `longitude`, `match_id`, `conversation_id`, `joined_at`, `last_read_message_id`, `typing_status`, `is_muted`, `iso_code`, `phone_code`, `code`, `discount_percentage`, `discount_amount`, `max_uses`, `current_uses`, `expires_at`, `counter_date`, `likes_sent`, `super_likes_sent`, `rewinds_used`, `profiles_viewed`, `device_id`, `device_name`, `os_version`, `app_version`, `last_active_at`, `device_type`, `push_token`, `otp_hash`, `verify_attempts`, `resend_attempts`, `is_verified`, `connection`, `queue`, `payload`, `exception`, `failed_at`, `category_id`, `payment_id`, `invoice_number`, `billing_address`, `pdf_url`, `native_name`, `user_agent`, `location`, `status`, `failure_reason`, `user1_id`, `user2_id`, `compatibility_score`, `is_unmatched`, `unmatched_by_id`, `unmatched_reason`) VALUES 
(NULL, 1, 'Test First name 87', 'Test Last name 33', 'test228@example.com', 'Test Password hash 44', 0, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, 'Test Action 85', 'Test Entity type 41', 1, 'Test Old values 34', 'Test New values 79', 'Test Ip address 41', 5, 'Test Note 37', 1, 1, 1, 'Test Reason 33', '2026-08-01 12:00:00', '2026-08-01 12:00:00', 74.16, 'Test Name 19', 1, 75.74, 10.92, 1, 1, '2026-08-01 12:00:00', 1, 1, 0, 'Test Iso code 10', 'Test Phone code 40', 'Test Code 54', 72.63, 19.33, 55, 61, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 58, 39, 93, 96, 1, 'Test Device name 44', 'Test Os version 32', 'Test App version 40', '2026-08-01 12:00:00', 'IOS', 'Test Push token 30', 'Test Otp hash 83', 60, 67, 1, 'Test Connection 57', 'Test Queue 77', 'Test Payload 36', 'Test Exception 8', '2026-08-01 12:00:00', 1, 1, 'Test Invoice number 5', 'Test Billing address 18', 'https://example.com/image.jpg', 'Test Native name 33', 'Test User agent 85', 'Test Location 29', 'SUCCESS', 'Test Failure reason 13', 1, 1, 63.37, 1, 1, 'Test Unmatched reason 8'),
(NULL, 1, 'Test First name 44', 'Test Last name 5', 'test723@example.com', 'Test Password hash 8', 1, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, 'Test Action 81', 'Test Entity type 96', 1, 'Test Old values 77', 'Test New values 6', 'Test Ip address 18', 6, 'Test Note 94', 1, 1, 1, 'Test Reason 21', '2026-08-01 12:00:00', '2026-08-01 12:00:00', 88.36, 'Test Name 23', 1, 25.21, 97.11, 1, 1, '2026-08-01 12:00:00', 1, 1, 0, 'Test Iso code 57', 'Test Phone code 97', 'Test Code 47', 74.47, 83.19, 91, 98, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 9, 26, 30, 100, 1, 'Test Device name 3', 'Test Os version 28', 'Test App version 35', '2026-08-01 12:00:00', 'IOS', 'Test Push token 60', 'Test Otp hash 25', 18, 19, 1, 'Test Connection 87', 'Test Queue 98', 'Test Payload 51', 'Test Exception 14', '2026-08-01 12:00:00', 1, 1, 'Test Invoice number 26', 'Test Billing address 71', 'https://example.com/image.jpg', 'Test Native name 22', 'Test User agent 72', 'Test Location 61', 'SUCCESS', 'Test Failure reason 75', 1, 1, 13.44, 1, 1, 'Test Unmatched reason 23'),
(NULL, 1, 'Test First name 22', 'Test Last name 8', 'test391@example.com', 'Test Password hash 61', 0, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, 'Test Action 76', 'Test Entity type 71', 1, 'Test Old values 85', 'Test New values 91', 'Test Ip address 22', 5, 'Test Note 85', 1, 1, 1, 'Test Reason 61', '2026-08-01 12:00:00', '2026-08-01 12:00:00', 66.16, 'Test Name 49', 1, 50.58, 66.12, 1, 1, '2026-08-01 12:00:00', 1, 0, 0, 'Test Iso code 46', 'Test Phone code 83', 'Test Code 97', 90.98, 51.82, 16, 96, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 29, 85, 100, 37, 1, 'Test Device name 72', 'Test Os version 73', 'Test App version 94', '2026-08-01 12:00:00', 'IOS', 'Test Push token 2', 'Test Otp hash 72', 9, 84, 0, 'Test Connection 51', 'Test Queue 49', 'Test Payload 85', 'Test Exception 50', '2026-08-01 12:00:00', 1, 1, 'Test Invoice number 35', 'Test Billing address 1', 'https://example.com/image.jpg', 'Test Native name 65', 'Test User agent 66', 'Test Location 66', 'SUCCESS', 'Test Failure reason 51', 1, 1, 12.98, 1, 1, 'Test Unmatched reason 36'),
(NULL, 1, 'Test First name 99', 'Test Last name 87', 'test805@example.com', 'Test Password hash 88', 1, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, 'Test Action 50', 'Test Entity type 23', 1, 'Test Old values 6', 'Test New values 24', 'Test Ip address 42', 6, 'Test Note 3', 1, 1, 1, 'Test Reason 98', '2026-08-01 12:00:00', '2026-08-01 12:00:00', 66.97, 'Test Name 31', 1, 45.85, 77.40, 1, 1, '2026-08-01 12:00:00', 1, 1, 1, 'Test Iso code 94', 'Test Phone code 74', 'Test Code 30', 13.89, 17.67, 89, 73, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 10, 45, 17, 56, 1, 'Test Device name 36', 'Test Os version 8', 'Test App version 65', '2026-08-01 12:00:00', 'IOS', 'Test Push token 90', 'Test Otp hash 79', 47, 33, 1, 'Test Connection 23', 'Test Queue 20', 'Test Payload 53', 'Test Exception 65', '2026-08-01 12:00:00', 1, 1, 'Test Invoice number 91', 'Test Billing address 86', 'https://example.com/image.jpg', 'Test Native name 48', 'Test User agent 56', 'Test Location 11', 'SUCCESS', 'Test Failure reason 18', 1, 1, 48.50, 0, 1, 'Test Unmatched reason 99'),
(NULL, 1, 'Test First name 18', 'Test Last name 97', 'test781@example.com', 'Test Password hash 78', 0, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, 'Test Action 21', 'Test Entity type 56', 1, 'Test Old values 12', 'Test New values 13', 'Test Ip address 39', 4, 'Test Note 72', 1, 1, 1, 'Test Reason 84', '2026-08-01 12:00:00', '2026-08-01 12:00:00', 29.36, 'Test Name 32', 1, 83.34, 79.23, 1, 1, '2026-08-01 12:00:00', 1, 1, 1, 'Test Iso code 2', 'Test Phone code 16', 'Test Code 39', 96.30, 81.58, 20, 86, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 71, 1, 69, 44, 1, 'Test Device name 85', 'Test Os version 76', 'Test App version 32', '2026-08-01 12:00:00', 'IOS', 'Test Push token 1', 'Test Otp hash 17', 42, 27, 0, 'Test Connection 58', 'Test Queue 49', 'Test Payload 58', 'Test Exception 54', '2026-08-01 12:00:00', 1, 1, 'Test Invoice number 42', 'Test Billing address 26', 'https://example.com/image.jpg', 'Test Native name 68', 'Test User agent 14', 'Test Location 91', 'SUCCESS', 'Test Failure reason 21', 1, 1, 59.30, 0, 1, 'Test Unmatched reason 22');

INSERT INTO `admin_audit_logs` (`id`, `admin_id`, `action`, `entity_type`, `entity_id`, `old_values`, `new_values`, `ip_address`, `created_at`) VALUES 
(NULL, 1, 'Test Action 73', 'Test Entity type 7', 1, 'Test Old values 69', 'Test New values 73', 'Test Ip address 6', NOW()),
(NULL, 1, 'Test Action 85', 'Test Entity type 100', 1, 'Test Old values 75', 'Test New values 89', 'Test Ip address 4', NOW()),
(NULL, 1, 'Test Action 68', 'Test Entity type 23', 1, 'Test Old values 68', 'Test New values 66', 'Test Ip address 51', NOW()),
(NULL, 1, 'Test Action 4', 'Test Entity type 66', 1, 'Test Old values 59', 'Test New values 46', 'Test Ip address 36', NOW()),
(NULL, 1, 'Test Action 19', 'Test Entity type 33', 1, 'Test Old values 44', 'Test New values 55', 'Test Ip address 25', NOW());

INSERT INTO `admin_notes` (`id`, `admin_id`, `user_id`, `note`, `created_at`) VALUES 
(NULL, 1, 6, 'Test Note 92', NOW()),
(NULL, 1, 5, 'Test Note 9', NOW()),
(NULL, 1, 5, 'Test Note 4', NOW()),
(NULL, 1, 4, 'Test Note 26', NOW()),
(NULL, 1, 5, 'Test Note 76', NOW());

INSERT INTO `admin_roles` (`admin_id`, `role_id`) VALUES 
(1, 1),
(1, 1),
(1, 1),
(1, 1),
(1, 1);

INSERT INTO `blocked_users` (`id`, `uuid`, `blocker_id`, `blocked_id`, `reason`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 1, 1, 'Test Reason 33', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 'Test Reason 83', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 'Test Reason 82', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 'Test Reason 3', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 'Test Reason 5', NOW(), '2026-08-01 12:00:00');

INSERT INTO `boosts` (`id`, `uuid`, `user_id`, `started_at`, `ends_at`, `multiplier`, `created_at`) VALUES 
(NULL, 1, 4, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 31.84, NOW()),
(NULL, 1, 5, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 86.52, NOW()),
(NULL, 1, 6, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 79.96, NOW()),
(NULL, 1, 5, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 20.20, NOW()),
(NULL, 1, 4, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 86.31, NOW());

INSERT INTO `cities` (`id`, `uuid`, `state_id`, `name`, `latitude`, `longitude`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 1, 'Test Name 67', 93.68, 23.66, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 49', 57.77, 74.31, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 22', 55.31, 30.26, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 23', 87.35, 65.37, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 97', 98.61, 94.61, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `conversations` (`id`, `uuid`, `match_id`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 1, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `conversation_participants` (`id`, `conversation_id`, `user_id`, `joined_at`, `last_read_message_id`, `typing_status`, `is_muted`) VALUES 
(NULL, 1, 5, '2026-08-01 12:00:00', 1, 0, 0),
(NULL, 1, 5, '2026-08-01 12:00:00', 1, 0, 0),
(NULL, 1, 6, '2026-08-01 12:00:00', 1, 1, 1),
(NULL, 1, 5, '2026-08-01 12:00:00', 1, 1, 1),
(NULL, 1, 5, '2026-08-01 12:00:00', 1, 0, 1);

INSERT INTO `countries` (`id`, `uuid`, `iso_code`, `name`, `phone_code`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Iso code 20', 'Test Name 18', 'Test Phone code 81', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Iso code 25', 'Test Name 39', 'Test Phone code 66', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Iso code 79', 'Test Name 6', 'Test Phone code 42', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Iso code 95', 'Test Name 13', 'Test Phone code 11', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Iso code 27', 'Test Name 2', 'Test Phone code 71', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `coupons` (`id`, `code`, `discount_percentage`, `discount_amount`, `max_uses`, `current_uses`, `expires_at`, `created_at`) VALUES 
(NULL, 'Test Code 94', 90.41, 56.36, 26, 70, '2026-08-01 12:00:00', NOW()),
(NULL, 'Test Code 39', 59.44, 25.11, 68, 30, '2026-08-01 12:00:00', NOW()),
(NULL, 'Test Code 26', 99.17, 78.83, 100, 27, '2026-08-01 12:00:00', NOW()),
(NULL, 'Test Code 50', 40.79, 30.43, 24, 57, '2026-08-01 12:00:00', NOW()),
(NULL, 'Test Code 32', 78.76, 22.11, 26, 54, '2026-08-01 12:00:00', NOW());

INSERT INTO `daily_user_counters` (`id`, `user_id`, `counter_date`, `likes_sent`, `super_likes_sent`, `rewinds_used`, `profiles_viewed`) VALUES 
(NULL, 6, '2026-08-01 12:00:00', 37, 36, 71, 94),
(NULL, 5, '2026-08-01 12:00:00', 51, 21, 50, 43),
(NULL, 5, '2026-08-01 12:00:00', 95, 80, 18, 77),
(NULL, 6, '2026-08-01 12:00:00', 90, 40, 64, 20),
(NULL, 6, '2026-08-01 12:00:00', 34, 24, 54, 60);

INSERT INTO `device_sessions` (`id`, `uuid`, `user_id`, `device_id`, `device_name`, `os_version`, `app_version`, `ip_address`, `last_active_at`, `is_active`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 4, 1, 'Test Device name 17', 'Test Os version 71', 'Test App version 16', 'Test Ip address 71', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 'Test Device name 7', 'Test Os version 3', 'Test App version 30', 'Test Ip address 93', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 'Test Device name 20', 'Test Os version 50', 'Test App version 59', 'Test Ip address 43', '2026-08-01 12:00:00', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 'Test Device name 48', 'Test Os version 25', 'Test App version 89', 'Test Ip address 72', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 'Test Device name 83', 'Test Os version 79', 'Test App version 76', 'Test Ip address 33', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00');

INSERT INTO `device_tokens` (`id`, `uuid`, `user_id`, `device_type`, `push_token`, `is_active`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 5, 'IOS', 'Test Push token 66', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 'IOS', 'Test Push token 24', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 'IOS', 'Test Push token 87', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 'IOS', 'Test Push token 86', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 'IOS', 'Test Push token 25', 1, NOW(), '2026-08-01 12:00:00');

INSERT INTO `failed_jobs` (`id`, `uuid`, `connection`, `queue`, `payload`, `exception`, `failed_at`) VALUES 
(NULL, 1, 'Test Connection 80', 'Test Queue 39', 'Test Payload 75', 'Test Exception 69', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Connection 9', 'Test Queue 76', 'Test Payload 8', 'Test Exception 5', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Connection 53', 'Test Queue 56', 'Test Payload 89', 'Test Exception 53', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Connection 83', 'Test Queue 55', 'Test Payload 3', 'Test Exception 9', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Connection 36', 'Test Queue 3', 'Test Payload 62', 'Test Exception 33', '2026-08-01 12:00:00');

INSERT INTO `hobbies` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 88', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 40', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 89', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 81', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 59', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `interests` (`id`, `uuid`, `category_id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 1, 'Test Name 81', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 42', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 85', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 74', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 12', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `interest_categories` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 51', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 52', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 75', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 41', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 30', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `invoices` (`id`, `payment_id`, `user_id`, `invoice_number`, `billing_address`, `pdf_url`, `created_at`) VALUES 
(NULL, 1, 4, 'Test Invoice number 2', 'Test Billing address 63', 'https://example.com/image.jpg', NOW()),
(NULL, 1, 4, 'Test Invoice number 92', 'Test Billing address 31', 'https://example.com/image.jpg', NOW()),
(NULL, 1, 6, 'Test Invoice number 28', 'Test Billing address 7', 'https://example.com/image.jpg', NOW()),
(NULL, 1, 5, 'Test Invoice number 37', 'Test Billing address 48', 'https://example.com/image.jpg', NOW()),
(NULL, 1, 5, 'Test Invoice number 74', 'Test Billing address 81', 'https://example.com/image.jpg', NOW());

INSERT INTO `languages` (`id`, `uuid`, `code`, `name`, `native_name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Code 24', 'Test Name 45', 'Test Native name 54', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Code 40', 'Test Name 80', 'Test Native name 78', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Code 99', 'Test Name 49', 'Test Native name 11', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Code 43', 'Test Name 66', 'Test Native name 23', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Code 100', 'Test Name 30', 'Test Native name 24', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `location_history` (`id`, `user_id`, `latitude`, `longitude`, `created_at`) VALUES 
(NULL, 6, 83.23, 77.32, NOW()),
(NULL, 6, 60.75, 36.85, NOW()),
(NULL, 5, 16.37, 99.86, NOW()),
(NULL, 5, 70.31, 60.84, NOW()),
(NULL, 5, 17.37, 85.98, NOW());

INSERT INTO `login_history` (`id`, `uuid`, `user_id`, `ip_address`, `user_agent`, `location`, `status`, `failure_reason`, `created_at`) VALUES 
(NULL, 1, 4, 'Test Ip address 46', 'Test User agent 53', 'Test Location 33', 'SUCCESS', 'Test Failure reason 72', NOW()),
(NULL, 1, 4, 'Test Ip address 38', 'Test User agent 62', 'Test Location 97', 'SUCCESS', 'Test Failure reason 23', NOW()),
(NULL, 1, 6, 'Test Ip address 61', 'Test User agent 96', 'Test Location 28', 'SUCCESS', 'Test Failure reason 91', NOW()),
(NULL, 1, 5, 'Test Ip address 66', 'Test User agent 43', 'Test Location 74', 'SUCCESS', 'Test Failure reason 10', NOW()),
(NULL, 1, 5, 'Test Ip address 69', 'Test User agent 49', 'Test Location 38', 'SUCCESS', 'Test Failure reason 98', NOW());

INSERT INTO `love_languages` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 2', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 35', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 51', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 50', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 64', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `matches` (`id`, `uuid`, `user1_id`, `user2_id`, `compatibility_score`, `is_unmatched`, `unmatched_by_id`, `unmatched_reason`, `created_at`, `updated_at`, `conversation_id`, `sender_id`, `content`, `message_type`, `reply_to_id`, `status`, `is_pinned`, `deleted_at`) VALUES 
(NULL, 1, 1, 1, 88.10, 1, 1, 'Test Unmatched reason 15', NOW(), '2026-08-01 12:00:00', 1, 1, 'Test Content 89', 'TEXT', 1, 'SENT', 0, '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 48.91, 1, 1, 'Test Unmatched reason 37', NOW(), '2026-08-01 12:00:00', 1, 1, 'Test Content 37', 'TEXT', 1, 'SENT', 1, '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 83.49, 1, 1, 'Test Unmatched reason 72', NOW(), '2026-08-01 12:00:00', 1, 1, 'Test Content 20', 'TEXT', 1, 'SENT', 0, '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 84.80, 1, 1, 'Test Unmatched reason 56', NOW(), '2026-08-01 12:00:00', 1, 1, 'Test Content 91', 'TEXT', 1, 'SENT', 1, '2026-08-01 12:00:00'),
(NULL, 1, 1, 1, 92.64, 1, 1, 'Test Unmatched reason 24', NOW(), '2026-08-01 12:00:00', 1, 1, 'Test Content 88', 'TEXT', 1, 'SENT', 1, '2026-08-01 12:00:00');

INSERT INTO `message_attachments` (`id`, `uuid`, `message_id`, `file_url`, `file_type`, `file_size_bytes`, `duration_seconds`, `metadata`, `created_at`) VALUES 
(NULL, 1, 1, 'https://example.com/image.jpg', 'Test File type 77', 96, 3, 'Test Metadata 91', NOW()),
(NULL, 1, 1, 'https://example.com/image.jpg', 'Test File type 71', 99, 18, 'Test Metadata 95', NOW()),
(NULL, 1, 1, 'https://example.com/image.jpg', 'Test File type 3', 7, 34, 'Test Metadata 53', NOW()),
(NULL, 1, 1, 'https://example.com/image.jpg', 'Test File type 51', 29, 60, 'Test Metadata 43', NOW()),
(NULL, 1, 1, 'https://example.com/image.jpg', 'Test File type 1', 6, 49, 'Test Metadata 79', NOW());

INSERT INTO `message_reactions` (`id`, `message_id`, `user_id`, `reaction_emoji`, `created_at`) VALUES 
(NULL, 1, 5, 'Test Reaction emoji 59', NOW()),
(NULL, 1, 5, 'Test Reaction emoji 93', NOW()),
(NULL, 1, 5, 'Test Reaction emoji 11', NOW()),
(NULL, 1, 6, 'Test Reaction emoji 50', NOW()),
(NULL, 1, 4, 'Test Reaction emoji 10', NOW());

INSERT INTO `moderation_queues` (`id`, `entity_type`, `entity_id`, `priority`, `status`, `flag_reason`, `created_at`) VALUES 
(NULL, 'USER_PROFILE', 1, 87, 'PENDING', 'Test Flag reason 70', NOW()),
(NULL, 'USER_PROFILE', 1, 92, 'PENDING', 'Test Flag reason 40', NOW()),
(NULL, 'USER_PROFILE', 1, 25, 'PENDING', 'Test Flag reason 10', NOW()),
(NULL, 'USER_PROFILE', 1, 63, 'PENDING', 'Test Flag reason 24', NOW()),
(NULL, 'USER_PROFILE', 1, 7, 'PENDING', 'Test Flag reason 50', NOW());

INSERT INTO `movie_genres` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 49', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 93', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 37', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 38', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 90', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `music_genres` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 46', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 32', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 84', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 76', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 41', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `notifications` (`id`, `uuid`, `user_id`, `type`, `title`, `body`, `reference_id`, `is_read`, `created_at`) VALUES 
(NULL, 1, 4, 'Test Type 51', 'Test Title 92', 'Test Body 64', 1, 0, NOW()),
(NULL, 1, 5, 'Test Type 44', 'Test Title 99', 'Test Body 28', 1, 0, NOW()),
(NULL, 1, 4, 'Test Type 84', 'Test Title 58', 'Test Body 34', 1, 1, NOW()),
(NULL, 1, 6, 'Test Type 17', 'Test Title 91', 'Test Body 97', 1, 1, NOW()),
(NULL, 1, 5, 'Test Type 34', 'Test Title 81', 'Test Body 52', 1, 1, NOW());

INSERT INTO `occupations` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 1', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 54', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 99', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 15', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 16', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `payments` (`id`, `uuid`, `user_id`, `amount`, `currency`, `status`, `payment_method`, `transaction_id`, `receipt_data`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 6, 10.38, 'Test Currency 51', 'PENDING', 'Test Payment method 75', 1, 'Test Receipt data 63', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 94.81, 'Test Currency 33', 'PENDING', 'Test Payment method 14', 1, 'Test Receipt data 71', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 77.37, 'Test Currency 73', 'PENDING', 'Test Payment method 44', 1, 'Test Receipt data 38', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 38.69, 'Test Currency 99', 'PENDING', 'Test Payment method 37', 1, 'Test Receipt data 93', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 94.92, 'Test Currency 37', 'PENDING', 'Test Payment method 67', 1, 'Test Receipt data 41', NOW(), '2026-08-01 12:00:00');

INSERT INTO `permissions` (`id`, `name`, `description`) VALUES 
(NULL, 'Test Name 86', 'Test Description 65'),
(NULL, 'Test Name 37', 'Test Description 57'),
(NULL, 'Test Name 88', 'Test Description 58'),
(NULL, 'Test Name 23', 'Test Description 55'),
(NULL, 'Test Name 94', 'Test Description 3');

INSERT INTO `personal_access_tokens` (`id`, `tokenable_type`, `tokenable_id`, `name`, `token`, `abilities`, `last_used_at`, `expires_at`, `created_at`, `updated_at`) VALUES 
(NULL, 'Test Tokenable type 68', 1, 'Test Name 57', 'Test Token 10', 'Test Abilities 36', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 'Test Tokenable type 14', 1, 'Test Name 57', 'Test Token 83', 'Test Abilities 98', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 'Test Tokenable type 67', 1, 'Test Name 2', 'Test Token 24', 'Test Abilities 98', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 'Test Tokenable type 2', 1, 'Test Name 80', 'Test Token 44', 'Test Abilities 3', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 'Test Tokenable type 11', 1, 'Test Name 43', 'Test Token 94', 'Test Abilities 88', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `pets` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 9', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 22', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 44', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 16', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 12', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `profile_prompts` (`id`, `uuid`, `prompt_text`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Prompt text 84', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Prompt text 42', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Prompt text 64', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Prompt text 16', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Prompt text 41', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `profile_visitors` (`id`, `visitor_id`, `visited_id`, `visited_at`) VALUES 
(NULL, 1, 1, '2026-08-01 12:00:00'),
(NULL, 1, 1, '2026-08-01 12:00:00'),
(NULL, 1, 1, '2026-08-01 12:00:00'),
(NULL, 1, 1, '2026-08-01 12:00:00'),
(NULL, 1, 1, '2026-08-01 12:00:00');

INSERT INTO `recommendation_queues` (`id`, `user_id`, `recommended_user_id`, `score`, `is_viewed`, `created_at`) VALUES 
(NULL, 5, 4, 96.43, 1, NOW()),
(NULL, 4, 4, 81.84, 0, NOW()),
(NULL, 4, 6, 41.34, 1, NOW()),
(NULL, 5, 5, 47.46, 1, NOW()),
(NULL, 5, 4, 42.98, 1, NOW());

INSERT INTO `refresh_tokens` (`id`, `uuid`, `user_id`, `session_id`, `token_hash`, `expires_at`, `is_revoked`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 4, 1, 'Test Token hash 22', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'Test Token hash 76', '2026-08-01 12:00:00', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'Test Token hash 70', '2026-08-01 12:00:00', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 'Test Token hash 11', '2026-08-01 12:00:00', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 'Test Token hash 85', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00');

INSERT INTO `reports` (`id`, `uuid`, `reporter_id`, `reported_id`, `reason_category`, `description`, `status`, `action_taken`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 6, 4, 'Test Reason category 78', 'Test Description 21', 'PENDING', 'Test Action taken 95', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 5, 'Test Reason category 12', 'Test Description 43', 'PENDING', 'Test Action taken 89', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 6, 'Test Reason category 95', 'Test Description 65', 'PENDING', 'Test Action taken 65', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 5, 'Test Reason category 22', 'Test Description 96', 'PENDING', 'Test Action taken 3', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 6, 'Test Reason category 16', 'Test Description 80', 'PENDING', 'Test Action taken 55', NOW(), '2026-08-01 12:00:00');

INSERT INTO `rewinds` (`id`, `uuid`, `user_id`, `swipe_id`, `created_at`) VALUES 
(NULL, 1, 6, 1, NOW()),
(NULL, 1, 5, 1, NOW()),
(NULL, 1, 4, 1, NOW()),
(NULL, 1, 5, 1, NOW()),
(NULL, 1, 5, 1, NOW());

INSERT INTO `roles` (`id`, `name`, `description`) VALUES 
(NULL, 'Test Name 58', 'Test Description 29'),
(NULL, 'Test Name 36', 'Test Description 89'),
(NULL, 'Test Name 17', 'Test Description 66'),
(NULL, 'Test Name 19', 'Test Description 57'),
(NULL, 'Test Name 53', 'Test Description 96');

INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES 
(1, 1),
(1, 1),
(1, 1),
(1, 1),
(1, 1);

INSERT INTO `security_logs` (`id`, `uuid`, `user_id`, `event_type`, `ip_address`, `details`, `created_at`) VALUES 
(NULL, 1, 5, 'Test Event type 11', 'Test Ip address 4', 'Test Details 36', NOW()),
(NULL, 1, 4, 'Test Event type 36', 'Test Ip address 20', 'Test Details 43', NOW()),
(NULL, 1, 4, 'Test Event type 86', 'Test Ip address 31', 'Test Details 14', NOW()),
(NULL, 1, 6, 'Test Event type 6', 'Test Ip address 69', 'Test Details 39', NOW()),
(NULL, 1, 4, 'Test Event type 43', 'Test Ip address 91', 'Test Details 23', NOW());

INSERT INTO `sports` (`id`, `uuid`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 'Test Name 43', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 14', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 84', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 56', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 25', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `states` (`id`, `uuid`, `country_id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 1, 'Test Name 30', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 43', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 88', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 61', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 1, 'Test Name 79', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `subscription_plans` (`id`, `uuid`, `name`, `tier_level`, `billing_cycle`, `price`, `currency`, `features`, `is_active`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 'Test Name 92', 41, 'WEEKLY', 49.29, 'Test Currency 52', 'Test Features 68', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 51', 21, 'WEEKLY', 31.72, 'Test Currency 48', 'Test Features 42', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 1', 4, 'WEEKLY', 79.66, 'Test Currency 19', 'Test Features 25', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 72', 96, 'WEEKLY', 68.86, 'Test Currency 65', 'Test Features 37', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 'Test Name 62', 66, 'WEEKLY', 11.85, 'Test Currency 86', 'Test Features 85', 1, NOW(), '2026-08-01 12:00:00');

INSERT INTO `swipes` (`id`, `uuid`, `swiper_id`, `swipee_id`, `swipe_type`, `is_rewound`, `created_at`) VALUES 
(NULL, 1, 5, 4, 'LIKE', 0, NOW()),
(NULL, 1, 6, 4, 'LIKE', 1, NOW()),
(NULL, 1, 4, 5, 'LIKE', 0, NOW()),
(NULL, 1, 4, 6, 'LIKE', 1, NOW()),
(NULL, 1, 6, 6, 'LIKE', 1, NOW());

INSERT INTO `user_authentications` (`id`, `uuid`, `user_id`, `auth_provider`, `provider_id`, `password_hash`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 6, 1, 1, 'Test Password hash 33', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 1, 'Test Password hash 88', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 1, 'Test Password hash 79', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 1, 'Test Password hash 27', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 1, 'Test Password hash 24', NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `user_hobbies` (`user_id`, `hobby_id`) VALUES 
(6, 1),
(5, 1),
(5, 1),
(5, 1),
(6, 1);

INSERT INTO `user_interests` (`user_id`, `interest_id`) VALUES 
(4, 1),
(5, 1),
(6, 1),
(4, 1),
(4, 1);

INSERT INTO `user_languages` (`user_id`, `language_id`) VALUES 
(6, 1),
(6, 1),
(5, 1),
(5, 1),
(5, 1);

INSERT INTO `user_locations` (`id`, `user_id`, `latitude`, `longitude`, `geohash`, `city_name`, `is_travel_mode`, `updated_at`) VALUES 
(NULL, 4, 36.14, 69.45, 'Test Geohash 39', 'Test City name 58', 0, '2026-08-01 12:00:00'),
(NULL, 5, 91.22, 75.87, 'Test Geohash 94', 'Test City name 79', 1, '2026-08-01 12:00:00'),
(NULL, 5, 52.96, 46.17, 'Test Geohash 79', 'Test City name 86', 0, '2026-08-01 12:00:00'),
(NULL, 6, 99.60, 59.13, 'Test Geohash 54', 'Test City name 9', 0, '2026-08-01 12:00:00'),
(NULL, 4, 29.44, 89.63, 'Test Geohash 99', 'Test City name 82', 0, '2026-08-01 12:00:00');

INSERT INTO `user_music_genres` (`user_id`, `music_genre_id`) VALUES 
(5, 1),
(6, 1),
(6, 1),
(6, 1),
(5, 1);

INSERT INTO `user_preference_children` (`user_id`, `children_id`) VALUES 
(5, 1),
(4, 1),
(6, 1),
(5, 1),
(6, 1);

INSERT INTO `user_preference_languages` (`user_id`, `language_id`) VALUES 
(6, 1),
(6, 1),
(6, 1),
(6, 1),
(6, 1);

INSERT INTO `user_preference_pets` (`user_id`, `pets_id`) VALUES 
(4, 1),
(5, 1),
(6, 1),
(4, 1),
(5, 1);

INSERT INTO `user_preference_politics` (`user_id`, `political_view_id`) VALUES 
(6, 1),
(4, 1),
(6, 1),
(4, 1),
(5, 1);

INSERT INTO `user_profile_prompts` (`id`, `uuid`, `user_id`, `prompt_id`, `answer_text`, `display_order`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 6, 1, 'Test Answer text 93', 20, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'Test Answer text 59', 70, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 'Test Answer text 43', 51, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'Test Answer text 22', 56, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'Test Answer text 52', 86, NOW(), '2026-08-01 12:00:00');

INSERT INTO `user_sports` (`user_id`, `sport_id`) VALUES 
(6, 1),
(4, 1),
(4, 1),
(6, 1),
(4, 1);

INSERT INTO `user_subscriptions` (`id`, `uuid`, `user_id`, `plan_id`, `status`, `platform`, `platform_subscription_id`, `starts_at`, `ends_at`, `auto_renew`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 5, 1, 'ACTIVE', 'APPLE', 1, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 'ACTIVE', 'APPLE', 1, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 'ACTIVE', 'APPLE', 1, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 0, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 'ACTIVE', 'APPLE', 1, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 1, 'ACTIVE', 'APPLE', 1, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, NOW(), '2026-08-01 12:00:00');

INSERT INTO `user_videos` (`id`, `uuid`, `user_id`, `video_url`, `thumbnail_url`, `duration_seconds`, `display_order`, `created_at`, `updated_at`, `deleted_at`) VALUES 
(NULL, 1, 5, 1, 'https://example.com/image.jpg', 67, 22, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'https://example.com/image.jpg', 91, 10, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'https://example.com/image.jpg', 4, 51, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 4, 1, 'https://example.com/image.jpg', 14, 30, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00'),
(NULL, 1, 5, 1, 'https://example.com/image.jpg', 29, 67, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00');

INSERT INTO `verification_requests` (`id`, `uuid`, `user_id`, `selfie_photo_url`, `status`, `reviewed_by`, `rejection_reason`, `created_at`, `updated_at`) VALUES 
(NULL, 1, 4, 'https://example.com/image.jpg', 'PENDING', 42, 'Test Rejection reason 95', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 4, 'https://example.com/image.jpg', 'PENDING', 36, 'Test Rejection reason 93', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 'https://example.com/image.jpg', 'PENDING', 16, 'Test Rejection reason 21', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 5, 'https://example.com/image.jpg', 'PENDING', 56, 'Test Rejection reason 80', NOW(), '2026-08-01 12:00:00'),
(NULL, 1, 6, 'https://example.com/image.jpg', 'PENDING', 88, 'Test Rejection reason 65', NOW(), '2026-08-01 12:00:00');

INSERT INTO `wallet_transactions` (`id`, `uuid`, `wallet_id`, `transaction_type`, `item_type`, `amount`, `description`, `created_at`) VALUES 
(NULL, 1, 1, 'EARN', 'COINS', 14, 'Test Description 57', NOW()),
(NULL, 1, 1, 'EARN', 'COINS', 50, 'Test Description 82', NOW()),
(NULL, 1, 1, 'EARN', 'COINS', 72, 'Test Description 75', NOW()),
(NULL, 1, 1, 'EARN', 'COINS', 27, 'Test Description 56', NOW()),
(NULL, 1, 1, 'EARN', 'COINS', 24, 'Test Description 50', NOW());

INSERT INTO `explore_interests` (`id`, `name`, `icon`, `sort_order`, `created_at`) VALUES 
(NULL, 'Test Name 19', 'https://example.com/image.jpg', 19, NOW()),
(NULL, 'Test Name 19', 'https://example.com/image.jpg', 45, NOW()),
(NULL, 'Test Name 54', 'https://example.com/image.jpg', 28, NOW()),
(NULL, 'Test Name 13', 'https://example.com/image.jpg', 12, NOW()),
(NULL, 'Test Name 5', 'https://example.com/image.jpg', 94, NOW());

INSERT INTO `explore_trending_categories` (`id`, `name`, `image_url`, `sort_order`, `created_at`) VALUES 
(NULL, 'Test Name 71', 'https://example.com/image.jpg', 80, NOW()),
(NULL, 'Test Name 44', 'https://example.com/image.jpg', 53, NOW()),
(NULL, 'Test Name 33', 'https://example.com/image.jpg', 68, NOW()),
(NULL, 'Test Name 41', 'https://example.com/image.jpg', 61, NOW()),
(NULL, 'Test Name 60', 'https://example.com/image.jpg', 26, NOW());

INSERT INTO `user_daily_picks` (`id`, `user_id`, `target_user_id`, `created_at`) VALUES 
(NULL, 5, 6, NOW()),
(NULL, 5, 6, NOW()),
(NULL, 6, 4, NOW()),
(NULL, 6, 4, NOW()),
(NULL, 4, 6, NOW());

INSERT INTO `user_interactions` (`id`, `user_id`, `target_user_id`, `type`, `created_at`) VALUES 
(NULL, 5, 6, 'LIKE', NOW()),
(NULL, 5, 5, 'LIKE', NOW()),
(NULL, 5, 5, 'LIKE', NOW()),
(NULL, 5, 5, 'LIKE', NOW()),
(NULL, 4, 5, 'LIKE', NOW());

INSERT INTO `user_views` (`id`, `viewer_id`, `user_id`, `viewed_at`) VALUES 
(NULL, 6, 4, NOW()),
(NULL, 6, 5, NOW()),
(NULL, 4, 5, NOW()),
(NULL, 4, 5, NOW()),
(NULL, 4, 5, NOW());

INSERT INTO `messages` (`id`, `uuid`, `conversation_id`, `sender_id`, `content`, `message_type`, `reply_to_id`, `status`, `is_pinned`, `created_at`, `updated_at`, `deleted_at`, `message_id`, `file_url`, `file_type`, `file_size_bytes`, `duration_seconds`, `metadata`, `user_id`, `reaction_emoji`, `migration`, `batch`, `entity_type`, `entity_id`, `priority`, `flag_reason`, `name`, `type`, `title`, `body`, `reference_id`, `is_read`, `display_order`, `identifier`, `code_hash`, `expires_at`, `is_used`, `amount`, `currency`, `payment_method`, `transaction_id`, `receipt_data`, `description`, `tokenable_type`, `tokenable_id`, `token`, `abilities`, `last_used_at`, `prompt_text`, `visitor_id`, `visited_id`, `visited_at`, `recommended_user_id`, `score`, `is_viewed`, `session_id`, `token_hash`, `is_revoked`, `email`, `reporter_id`, `reported_id`, `reason_category`, `action_taken`, `swipe_id`, `role_id`, `permission_id`, `event_type`, `ip_address`, `details`, `country_id`, `tier_level`, `billing_cycle`, `price`, `features`, `is_active`, `swiper_id`, `swipee_id`, `swipe_type`, `is_rewound`, `first_name`, `last_name`, `display_name`, `phone`, `birth_date`, `age`, `gender_identity_id`, `interested_in_id`, `relationship_goal_id`, `onboarding_completed`, `is_premium`, `last_seen`, `last_online_at`, `total_profile_views`, `total_likes_received`, `total_likes_sent`, `total_matches`, `auth_provider`, `provider_id`, `password_hash`, `hobby_id`, `interest_id`, `language_id`, `latitude`, `longitude`, `geohash`, `city_name`, `is_travel_mode`, `preferred_age_min`, `preferred_age_max`, `distance_radius_km`, `interested_gender_id`, `height_min_cm`, `height_max_cm`, `education_id`, `religion_id`, `smoking_id`, `drinking_id`, `online_only`, `verified_users_only`) VALUES 
(NULL, 1, 1, 1, 'Test Content 82', 'TEXT', 1, 'ACTIVE', 1, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, 'https://example.com/image.jpg', 'Test File type 7', 73, 89, 'Test Metadata 94', 5, 'Test Reaction emoji 9', 'Test Migration 75', 41, 'USER_PROFILE', 1, 31, 'Test Flag reason 99', 'Test Name 90', 'EMAIL_VERIFICATION', 'Test Title 30', 'Test Body 17', 1, 0, 46, 1, 'Test Code hash 15', '2026-08-01 12:00:00', 1, 59.99, 'Test Currency 83', 'Test Payment method 18', 1, 'Test Receipt data 2', 'Test Description 72', 'Test Tokenable type 33', 1, 'Test Token 33', 'Test Abilities 44', '2026-08-01 12:00:00', 'Test Prompt text 81', 1, 1, '2026-08-01 12:00:00', 5, 61.69, 0, 1, 'Test Token hash 59', 0, 'test381@example.com', 4, 4, 'Test Reason category 18', 'Test Action taken 65', 1, 1, 1, 'Test Event type 78', 'Test Ip address 54', 'Test Details 39', 1, 91, 'WEEKLY', 41.28, 'Test Features 4', 0, 5, 4, 'LIKE', 1, 'Test First name 5', 'Test Last name 23', 'Test Display name 89', 'Test Phone 48', '2026-08-01 12:00:00', 22, 1, 1, 1, 0, 0, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 84, 83, 80, 58, 1, 1, 'Test Password hash 32', 1, 1, 1, 64.24, 29.43, 'Test Geohash 30', 'Test City name 36', 1, 48, 27, 58, 1, 27, 69, 1, 1, 1, 1, 0, 0),
(NULL, 1, 1, 1, 'Test Content 26', 'TEXT', 1, 'ACTIVE', 0, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, 'https://example.com/image.jpg', 'Test File type 49', 15, 49, 'Test Metadata 38', 5, 'Test Reaction emoji 8', 'Test Migration 95', 60, 'USER_PROFILE', 1, 81, 'Test Flag reason 25', 'Test Name 47', 'EMAIL_VERIFICATION', 'Test Title 29', 'Test Body 68', 1, 0, 36, 1, 'Test Code hash 61', '2026-08-01 12:00:00', 1, 47.21, 'Test Currency 69', 'Test Payment method 12', 1, 'Test Receipt data 11', 'Test Description 100', 'Test Tokenable type 62', 1, 'Test Token 99', 'Test Abilities 4', '2026-08-01 12:00:00', 'Test Prompt text 37', 1, 1, '2026-08-01 12:00:00', 6, 92.81, 1, 1, 'Test Token hash 61', 1, 'test244@example.com', 6, 6, 'Test Reason category 73', 'Test Action taken 87', 1, 1, 1, 'Test Event type 10', 'Test Ip address 87', 'Test Details 97', 1, 60, 'WEEKLY', 13.26, 'Test Features 11', 1, 6, 6, 'LIKE', 1, 'Test First name 12', 'Test Last name 17', 'Test Display name 36', 'Test Phone 88', '2026-08-01 12:00:00', 3, 1, 1, 1, 1, 0, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 25, 34, 39, 29, 1, 1, 'Test Password hash 71', 1, 1, 1, 71.55, 26.59, 'Test Geohash 85', 'Test City name 30', 0, 64, 43, 68, 1, 86, 88, 1, 1, 1, 1, 0, 0),
(NULL, 1, 1, 1, 'Test Content 20', 'TEXT', 1, 'ACTIVE', 0, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, 'https://example.com/image.jpg', 'Test File type 81', 3, 24, 'Test Metadata 26', 6, 'Test Reaction emoji 90', 'Test Migration 2', 83, 'USER_PROFILE', 1, 14, 'Test Flag reason 2', 'Test Name 10', 'EMAIL_VERIFICATION', 'Test Title 55', 'Test Body 51', 1, 0, 44, 1, 'Test Code hash 79', '2026-08-01 12:00:00', 1, 29.92, 'Test Currency 59', 'Test Payment method 86', 1, 'Test Receipt data 36', 'Test Description 50', 'Test Tokenable type 56', 1, 'Test Token 76', 'Test Abilities 28', '2026-08-01 12:00:00', 'Test Prompt text 59', 1, 1, '2026-08-01 12:00:00', 6, 87.48, 1, 1, 'Test Token hash 40', 0, 'test125@example.com', 4, 4, 'Test Reason category 31', 'Test Action taken 5', 1, 1, 1, 'Test Event type 22', 'Test Ip address 9', 'Test Details 50', 1, 71, 'WEEKLY', 81.51, 'Test Features 73', 0, 5, 4, 'LIKE', 0, 'Test First name 54', 'Test Last name 12', 'Test Display name 88', 'Test Phone 8', '2026-08-01 12:00:00', 54, 1, 1, 1, 1, 1, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 86, 52, 38, 56, 1, 1, 'Test Password hash 33', 1, 1, 1, 79.42, 99.96, 'Test Geohash 12', 'Test City name 37', 0, 28, 20, 95, 1, 38, 65, 1, 1, 1, 1, 1, 1),
(NULL, 1, 1, 1, 'Test Content 97', 'TEXT', 1, 'ACTIVE', 0, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, 'https://example.com/image.jpg', 'Test File type 80', 61, 39, 'Test Metadata 3', 5, 'Test Reaction emoji 47', 'Test Migration 9', 60, 'USER_PROFILE', 1, 91, 'Test Flag reason 37', 'Test Name 47', 'EMAIL_VERIFICATION', 'Test Title 8', 'Test Body 41', 1, 1, 30, 1, 'Test Code hash 64', '2026-08-01 12:00:00', 1, 37.28, 'Test Currency 45', 'Test Payment method 34', 1, 'Test Receipt data 90', 'Test Description 8', 'Test Tokenable type 68', 1, 'Test Token 93', 'Test Abilities 44', '2026-08-01 12:00:00', 'Test Prompt text 16', 1, 1, '2026-08-01 12:00:00', 5, 12.12, 1, 1, 'Test Token hash 98', 1, 'test835@example.com', 5, 4, 'Test Reason category 23', 'Test Action taken 89', 1, 1, 1, 'Test Event type 40', 'Test Ip address 70', 'Test Details 8', 1, 4, 'WEEKLY', 44.24, 'Test Features 97', 0, 4, 5, 'LIKE', 0, 'Test First name 51', 'Test Last name 57', 'Test Display name 94', 'Test Phone 44', '2026-08-01 12:00:00', 69, 1, 1, 1, 0, 1, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 21, 59, 46, 98, 1, 1, 'Test Password hash 78', 1, 1, 1, 62.10, 86.21, 'Test Geohash 50', 'Test City name 17', 1, 98, 41, 69, 1, 27, 5, 1, 1, 1, 1, 0, 1),
(NULL, 1, 1, 1, 'Test Content 57', 'TEXT', 1, 'ACTIVE', 0, NOW(), '2026-08-01 12:00:00', '2026-08-01 12:00:00', 1, 'https://example.com/image.jpg', 'Test File type 34', 41, 1, 'Test Metadata 79', 6, 'Test Reaction emoji 20', 'Test Migration 80', 71, 'USER_PROFILE', 1, 2, 'Test Flag reason 72', 'Test Name 16', 'EMAIL_VERIFICATION', 'Test Title 12', 'Test Body 50', 1, 1, 75, 1, 'Test Code hash 55', '2026-08-01 12:00:00', 0, 21.87, 'Test Currency 3', 'Test Payment method 62', 1, 'Test Receipt data 39', 'Test Description 56', 'Test Tokenable type 43', 1, 'Test Token 24', 'Test Abilities 17', '2026-08-01 12:00:00', 'Test Prompt text 12', 1, 1, '2026-08-01 12:00:00', 4, 80.97, 0, 1, 'Test Token hash 25', 0, 'test353@example.com', 4, 4, 'Test Reason category 20', 'Test Action taken 64', 1, 1, 1, 'Test Event type 28', 'Test Ip address 31', 'Test Details 26', 1, 27, 'WEEKLY', 17.90, 'Test Features 57', 1, 5, 4, 'LIKE', 0, 'Test First name 78', 'Test Last name 39', 'Test Display name 37', 'Test Phone 36', '2026-08-01 12:00:00', 100, 1, 1, 1, 0, 0, '2026-08-01 12:00:00', '2026-08-01 12:00:00', 67, 81, 72, 27, 1, 1, 'Test Password hash 90', 1, 1, 1, 82.56, 55.90, 'Test Geohash 54', 'Test City name 27', 0, 70, 100, 76, 1, 81, 86, 1, 1, 1, 1, 1, 1);

